name: Laru Data Analysis

on:
  workflow_dispatch:

jobs:
  analyze_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          # POISTETTIIN: cache-asetukset, jotka aiheuttivat herjan

      - name: Install dependencies
        run: pip install pandas numpy

      - name: Run analysis script
        run: python analysoi_laru.py
